/**
 * Created by jake.cox on 4/19/2017.
 */
import { Injectable } from '@angular/core';

export class Member {
  ID: number;
  Name: string;
  NameLastFirst: string;
  EnvelopeName: string;
  CurrentAge: string;
  Age: number;
  DisplayGender: string;
  Relationship: string;
  RelationshipValue: string;
  DisplayTerminationDate: string;
  MiddleInitial: string;
  IsPrimary: boolean;
  IsSpouse: boolean;
  IsChild: boolean;
  IsGrandChild: boolean;
  Number: number;
  ERID: string;
  CreatedDate: string;
  CreatedBy: string;
  ModifiedDate: string;
  ModifiedBy: string;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  NameSuffix: string;
  Gender: string;
  FK_lmsValue_Status: string;
  FK_cdvID: number;
  FK_ceeID_EEClass1: number;
  FK_ceeID_EEClass2: number;
  DateOfHire: string;
  DateOfDeath: string;
  HomeAddressLine1: string;
  HomeAddressLine2: string;
  HomeCity: string;
  HomeState: string;
  HomeZipCode: string;
  HomeCountry: string;
  HomeEmail: string;
  HomePhone: string;
  WorkJobTitle: string;
  WorkPhoneExt: string;
  WorkPhone: string;
  CellPhone: string;
  UDF1: string;
  UDF2: string;
  UDF3: string;
  UDF4: string;
  UDF5: string;
  FK_comID: number;
  EnrollmentUID: string;
  EnrollmentPassword: string;
  DateOfTermination: string;
  WorkHours: number;
  FK_lutValue_EmploymentStatus: string;
  IsMedicare: boolean;
  WorkEmailAddress: string;
  FK_cipID_ImportProcess: number;
  EnrollmentPWDReset: boolean;
  MedicareClaimNumber: string;
  MedicareApplicationSigDate: string;
  PayrollNumber: string;
  DateOfEligibility: string;
  FK_clnID_Location: number;
  EnrollmentIsValidated: boolean;
  DateNewHireModeCompleted: string;
  IsTest: boolean;
  AgeAsOfToday: number;
  WorkState: string;
  CreatedFromProcess: string;
  ModifiedFromProcess: string;
  FK_ccdID_DeductionScheme: number;
}

let members: Member[] = [
  {
    'Name': 'KENS WOLFESCHLEGELSTEINHAUSENBE',
    'NameLastFirst': 'WOLFESCHLEGELSTEINHAUSENBE KENS',
    'EnvelopeName': 'WOLFESCHLEGELSTEINHAUSENBE_KENS',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 223240,
    'Number': 428544,
    'ERID': '123456',
    'CreatedDate': '/Date(1434551310000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1483258018000-0800)/',
    'ModifiedBy': 'START OF DAY SERVICE',
    'FirstName': 'KENS',
    'MiddleName': null,
    'LastName': 'WOLFESCHLEGELSTEINHAUSENBE',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 530,
    'DateOfHire': '/Date(1475737200000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': '2307 N. FINE',
    'HomeAddressLine2': null,
    'HomeCity': 'FRESNO',
    'HomeState': 'AL',
    'HomeZipCode': '93727',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': 'lansmank@admindirect.com',
    'HomePhone': null,
    'WorkJobTitle': 'TEST MEMBER',
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': 'lansmank@admindirect.com',
    'EnrollmentPassword': 'A648D7A0EF8174338249B3309B3A94B13FE469CE3750B5E018BA1234BE4202F2',
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 13999,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': '12345678',
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 377,
    'EnrollmentIsValidated': true,
    'DateNewHireModeCompleted': '/Date(1479801600000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': null,
    'ModifiedFromProcess': 'START OF DAY SERVICE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'MARK GUEVARA',
    'NameLastFirst': 'GUEVARA MARK',
    'EnvelopeName': 'GUEVARA_MARK',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 229897,
    'Number': 436048,
    'ERID': '345678',
    'CreatedDate': '/Date(1436372996000-0700)/',
    'CreatedBy': 'lacey.sagmaquen',
    'ModifiedDate': '/Date(1491616832000-0700)/',
    'ModifiedBy': 'hgs.mark.guevara',
    'FirstName': 'MARK',
    'MiddleName': null,
    'LastName': 'GUEVARA',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1427871600000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': '1234 FIFTH STREET',
    'HomeAddressLine2': null,
    'HomeCity': 'BOOMTOWN',
    'HomeState': 'CA',
    'HomeZipCode': '93777',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'PT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 13999,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 0,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 39,
    'WorkState': null,
    'CreatedFromProcess': null,
    'ModifiedFromProcess': 'MEMBER DEMOGRAPHIC UPDATE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'JOHN TEST',
    'NameLastFirst': 'TEST JOHN',
    'EnvelopeName': 'TEST_JOHN',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 236533,
    'Number': 443111,
    'ERID': '234567',
    'CreatedDate': '/Date(1438715675000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1473368712000-0700)/',
    'ModifiedBy': 'hgs.jesus.carrera',
    'FirstName': 'JOHN',
    'MiddleName': null,
    'LastName': 'TEST',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2056,
    'FK_ceeID_EEClass1': 0,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1438412400000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': '2307 N. FINE',
    'HomeAddressLine2': null,
    'HomeCity': 'FRESNO',
    'HomeState': 'CA',
    'HomeZipCode': '93727',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': 'jcarrera@admindirect.com',
    'HomePhone': '6193221722',
    'WorkJobTitle': 'PROGRAMMER ANALYST',
    'WorkPhone': '5593441212',
    'WorkPhoneExt': null,
    'CellPhone': '5593221722',
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': 'jcarrera@admindirect.com',
    'EnrollmentPassword': '056446EEB3952BE4AB49350033354772E2FCA195AED26EE7B3D185F124BE1C45',
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 40,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': 'jcarrera@admindirect.com',
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 0,
    'EnrollmentIsValidated': true,
    'DateNewHireModeCompleted': '/Date(1441436400000-0700)/',
    'IsTest': true,
    'AgeAsOfToday': 46,
    'WorkState': null,
    'CreatedFromProcess': null,
    'ModifiedFromProcess': 'Online Demographic Update',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'SALLY TEST',
    'NameLastFirst': 'TEST SALLY',
    'EnvelopeName': 'TEST_SALLY',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Female',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 339318,
    'Number': 554682,
    'ERID': null,
    'CreatedDate': '/Date(1460150061000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1491931600000-0700)/',
    'ModifiedBy': 'hgs.jake.cox',
    'FirstName': 'SALLY',
    'MiddleName': null,
    'LastName': 'TEST',
    'NameSuffix': null,
    'Gender': 'F',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1428476400000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': '2307 N. FINE',
    'HomeAddressLine2': '#1200',
    'HomeCity': 'FRESNO',
    'HomeState': 'CA',
    'HomeZipCode': '93727',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': '6193221722',
    'WorkJobTitle': null,
    'WorkPhone': '5593221722',
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': true,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': 'safasdf',
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 0,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': null,
    'ModifiedFromProcess': 'MEMBER DEMOGRAPHIC UPDATE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'SDFGSDGF XSDFGSDGF',
    'NameLastFirst': 'XSDFGSDGF SDFGSDGF',
    'EnvelopeName': 'XSDFGSDGF_SDFGSDGF',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 374303,
    'Number': 591978,
    'ERID': null,
    'CreatedDate': '/Date(1464285811000-0700)/',
    'CreatedBy': 'hgs.jake.cox',
    'ModifiedDate': '/Date(1464291273000-0700)/',
    'ModifiedBy': 'END OF DAY SERVICE',
    'FirstName': 'SDFGSDGF',
    'MiddleName': null,
    'LastName': 'XSDFGSDGF',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 0,
    'FK_ceeID_EEClass1': 0,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1463468400000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': '234234',
    'HomeAddressLine2': null,
    'HomeCity': '234234',
    'HomeState': 'AK',
    'HomeZipCode': '654165126',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 0,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 0,
    'WorkState': null,
    'CreatedFromProcess': null,
    'ModifiedFromProcess': null,
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'ADMINEVENT TESTER',
    'NameLastFirst': 'TESTER ADMINEVENT',
    'EnvelopeName': 'TESTER_ADMINEVENT',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 407538,
    'Number': 630273,
    'ERID': null,
    'CreatedDate': '/Date(1472063252000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1473807263000-0700)/',
    'ModifiedBy': 'hgs.bret.dalldorf',
    'FirstName': 'ADMINEVENT',
    'MiddleName': null,
    'LastName': 'TESTER',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 0,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1471762800000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': 'ASD',
    'HomeAddressLine2': null,
    'HomeCity': 'ASDF',
    'HomeState': 'AK',
    'HomeZipCode': '12345',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': 'bdalldorf@admindirect.com',
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(1471762800000-0700)/',
    'FK_clnID_Location': 0,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(1473750000000-0700)/',
    'IsTest': true,
    'AgeAsOfToday': 26,
    'WorkState': null,
    'CreatedFromProcess': 'Create Member Wizard',
    'ModifiedFromProcess': 'Enroll Checkout Update NewHireModeCompleted',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'ACA TESTER',
    'NameLastFirst': 'TESTER ACA',
    'EnvelopeName': 'TESTER_ACA',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 422563,
    'Number': 647634,
    'ERID': null,
    'CreatedDate': '/Date(1474584331000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1483258028000-0800)/',
    'ModifiedBy': 'START OF DAY SERVICE',
    'FirstName': 'ACA',
    'MiddleName': null,
    'LastName': 'TESTER',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 529,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1420099200000-0800)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': 'ASDFSAD',
    'HomeAddressLine2': null,
    'HomeCity': 'SADASDF',
    'HomeState': 'AL',
    'HomeZipCode': '12345',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 377,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': false,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': 'Create Member Wizard',
    'ModifiedFromProcess': 'START OF DAY SERVICE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'ACA TESTER',
    'NameLastFirst': 'TESTER ACA',
    'EnvelopeName': 'TESTER_ACA',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 560327,
    'Number': 755413,
    'ERID': null,
    'CreatedDate': '/Date(1478391801000-0700)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1483257947000-0800)/',
    'ModifiedBy': 'START OF DAY SERVICE',
    'FirstName': 'ACA',
    'MiddleName': null,
    'LastName': 'TESTER',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1391241600000-0800)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': 'ASDFASDFASDF',
    'HomeAddressLine2': null,
    'HomeCity': 'ASDFASD',
    'HomeState': 'CA',
    'HomeZipCode': '12345',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': 'lansmank@admindirect.com',
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'PA',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 377,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': 'Create Member Wizard',
    'ModifiedFromProcess': 'START OF DAY SERVICE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'ACANEW TESTER',
    'NameLastFirst': 'TESTER ACANEW',
    'EnvelopeName': 'TESTER_ACANEW',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 565586,
    'Number': 761204,
    'ERID': null,
    'CreatedDate': '/Date(1478970536000-0800)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1483257991000-0800)/',
    'ModifiedBy': 'START OF DAY SERVICE',
    'FirstName': 'ACANEW',
    'MiddleName': null,
    'LastName': 'TESTER',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'A',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1459494000000-0700)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': 'FGHJFGHJFGHKJFGHJ',
    'HomeAddressLine2': null,
    'HomeCity': 'FGHJGFHJFGHJFGHJ',
    'HomeState': 'CA',
    'HomeZipCode': '12345',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(-59011459200000-0800)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(1459494000000-0700)/',
    'FK_clnID_Location': 377,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': 'Create Member Wizard',
    'ModifiedFromProcess': 'START OF DAY SERVICE',
    'FK_ccdID_DeductionScheme': 0
  },
  {
    'Name': 'ACA TESTERTWO',
    'NameLastFirst': 'TESTERTWO ACA',
    'EnvelopeName': 'TESTERTWO_ACA',
    'CurrentAge': '0',
    'Age': 0,
    'DisplayGender': 'Male',
    'Relationship': 'Member',
    'RelationshipValue': '',
    'DisplayTerminationDate': '10/11/2016',
    'MiddleInitial': '',
    'IsPrimary': true,
    'IsSpouse': false,
    'IsChild': false,
    'IsGrandChild': false,
    'ID': 570106,
    'Number': 766862,
    'ERID': null,
    'CreatedDate': '/Date(1479753331000-0800)/',
    'CreatedBy': 'lansmank',
    'ModifiedDate': '/Date(1483258019000-0800)/',
    'ModifiedBy': 'START OF DAY SERVICE',
    'FirstName': 'ACA',
    'MiddleName': null,
    'LastName': 'TESTERTWO',
    'NameSuffix': null,
    'Gender': 'M',
    'FK_lmsValue_Status': 'T',
    'FK_cdvID': 2053,
    'FK_ceeID_EEClass1': 528,
    'FK_ceeID_EEClass2': 0,
    'DateOfHire': '/Date(1449043200000-0800)/',
    'DateOfDeath': '/Date(-59011459200000-0800)/',
    'HomeAddressLine1': 'ASDFASDFASD',
    'HomeAddressLine2': null,
    'HomeCity': 'ASDFASDASD',
    'HomeState': 'CA',
    'HomeZipCode': '12345',
    'HomeCountry': 'UNITED STATES OF AMERICA',
    'HomeEmail': null,
    'HomePhone': null,
    'WorkJobTitle': null,
    'WorkPhone': null,
    'WorkPhoneExt': null,
    'CellPhone': null,
    'UDF1': null,
    'UDF2': null,
    'UDF3': null,
    'UDF4': null,
    'UDF5': null,
    'FK_comID': 169,
    'EnrollmentUID': null,
    'EnrollmentPassword': null,
    'DateOfTermination': '/Date(1476169200000-0700)/',
    'WorkHours': 0,
    'FK_lutValue_EmploymentStatus': 'FT',
    'IsMedicare': false,
    'WorkEmailAddress': null,
    'FK_cipID_ImportProcess': 0,
    'EnrollmentPWDReset': false,
    'MedicareClaimNumber': null,
    'MedicareApplicationSigDate': '/Date(-59011459200000-0800)/',
    'PayrollNumber': null,
    'DateOfEligibility': '/Date(-59011459200000-0800)/',
    'FK_clnID_Location': 377,
    'EnrollmentIsValidated': false,
    'DateNewHireModeCompleted': '/Date(-59011459200000-0800)/',
    'IsTest': true,
    'AgeAsOfToday': 27,
    'WorkState': null,
    'CreatedFromProcess': 'Create Member Wizard',
    'ModifiedFromProcess': 'START OF DAY SERVICE',
    'FK_ccdID_DeductionScheme': 0
  }
];

@Injectable()
export class MemberService {
  getMembers() {
    return members;
  }
}
